
from langgraph.prebuilt import create_react_agent
from tools import dbtool
from llm_initialization import llm
from output_classes import SubmitFinalAnswer






#agent to check the query generated by the query generation agent 
query_check_agent=create_react_agent(llm,prompt="""
                                     
                                     You are a PostgreSQL expert with a strong attention to detail.
                                                        Double check the PostgreSQL query for common mistakes, including:
                                                        - Using NOT IN with NULL values
                                                        - Using UNION when UNION ALL should have been used
                                                        - Using BETWEEN for exclusive ranges
                                                        - Data type mismatch in predicates
                                                        - Properly quoting identifiers
                                                        - Using the correct number of arguments for functions
                                                        - Casting to the correct data type
                                                        - Using the proper columns for joins

                                                        If there are any of the above mistakes, rewrite the query. If there are no mistakes, just reproduce the original query.
                                        ONLY OUTPUT THE SQL QUERY AND NOTHING ELSE. DO NOT OUTPUT ANYTHING ELSE
                                     """,tools=[])

#agent to generate a sql query based on the question and the relevant table schema 
query_gen_agent= create_react_agent(llm,prompt="""
                         
                                    You are a SQL expert with a strong attention to detail.

                                                Given an input question, output a syntactically correct Postgres query to run.

                                                When generating the query:
                                                Output the SQL query that answers the input question without a tool call.

                                                Unless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 5 results.
                                                You can order the results by a relevant column to return the most interesting examples in the database.

                                                If you get feedback to fix a query, you should fix the query and try again.
                                                DO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.
                                    
                             """,
                                        tools=[])


#agent to execute the generated sql query and present the results
query_executor_agent=create_react_agent(llm,prompt="""You are a SQL expert with a strong attention to detail.
                                        Fix the sql query if incorrect and  Execute the SQL query and return the result to the user using your tool.""",
                                        tools=dbtool, response_format=SubmitFinalAnswer)



